FROM golang:1.24 AS builder

WORKDIR /backend

COPY go.mod go.sum ./
RUN go mod tidy

COPY . .

RUN go build -o app .

FROM gcr.io/distroless/base-debian12 AS final

WORKDIR /app

COPY --from=builder /backend/app .
COPY --from=builder /backend/.env .

CMD ["./app"]
